#!/bin/bash

#Основная инфа
APP_NAME="PPPWN"
APP_BASE_DIR=
APP_LAN_INTERFACE=
APP_FW_VERSION=
APP_PID_FILE="/opt/var/run/pppwn.pid"
APP_LOG_FILE="/opt/var/log/pppwn.log"
APP_SERVER_PORT=9590
#Понты
COLOR_GREEN='\033[0;32m'
COLOR_WHITE='\033[1;37m'
COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_BLUE='\033[1;34m'

load_config()
{
	echo ""
	echo "Грузим конфиг..."
	APP_BASE_DIR=$(jq -r .basedir /opt/etc/pppwn.config.json)
	APP_LAN_INTERFACE=$(jq -r .interface /opt/etc/pppwn.config.json)
	APP_FW_VERSION=$(jq -r .fwversion /opt/etc/pppwn.config.json)
	return 1
}

start()
{
	if [ -f "$APP_PID_FILE" ]; then
        echo "$APP_NAME уже запущен."
        return 1
    fi
	load_config
	pppwn --interface $APP_LAN_INTERFACE --fw $APP_FW_VERSION --stage1 $APP_BASE_DIR/stage1_$APP_FW_VERSION.bin --stage2 $APP_BASE_DIR/stage2_$APP_FW_VERSION.bin --timeout 10 --auto-retry >> "$APP_LOG_FILE" 2>&1 &
	echo $! > "$APP_PID_FILE"
	echo -e "$COLOR_GREEN" "✓ $APP_NAME запущен успешно. $COLOR_WHITE"
	echo ""
}

app_stopped_message() {
	echo -e "$COLOR_RED ✗ $COLOR_WHITE $APP_NAME не запущен."
	echo ""
}

stop()
{
	echo ""
	if [ ! -f "$APP_PID_FILE" ]; then
        app_stopped_message
        return 1
    fi
    echo "Останавливаем $APP_NAME..."
    PID=$(cat "$APP_PID_FILE")
    kill $PID 2>/dev/null
    rm -f "$APP_PID_FILE"
    rm -f "$APP_LOG_FILE"
    echo -e "$COLOR_GREEN" "✓ Готово. $COLOR_WHITE"
	echo ""
}

restart()
{
	stop
	start
}

status()
{
	echo ""
	if [ ! -f "$APP_PID_FILE" ]; then
        app_stopped_message
        return 1
    fi
	load_config
	echo -e "Интерфейс: $COLOR_BLUE$APP_LAN_INTERFACE$COLOR_WHITE"
	echo -e "Прошивка: $COLOR_BLUE$APP_FW_VERSION$COLOR_WHITE"
	PID=$(cat "$APP_PID_FILE")
	echo -e "$APP_NAME работает (PID: $COLOR_BLUE$PID$COLOR_WHITE)"
	if [ ! -f "$APP_LOG_FILE" ]; then
        echo -e "$COLOR_RED Лог-файл не найден: $APP_LOG_FILE $COLOR_WHITE"
        return 1
    fi
	echo "═══════════════════════════════════════════════════"
    tail -n 50 "$APP_LOG_FILE"
    echo "═══════════════════════════════════════════════════"
}

help()
{
	echo ""
    echo -e "$COLOR_GREEN" "Команды CLI: $COLOR_WHITE"
    echo "  start     - Запустить $APP_NAME"
    echo "  stop      - Остановить $APP_NAME"
    echo "  restart   - Перезапустить"
    echo "  status    - Показать статус"
    echo -e "$COLOR_GREEN" "Команды для Web: $COLOR_WHITE"
    echo "  web_start - Запуск веб интерфейса"
	echo ""
}
web_start()
{
	load_config
	echo "Запускаем сервер: $(nvram get lan_ipaddr 2>&1):$APP_SERVER_PORT"
	php8-cli -S 0.0.0.0:$APP_SERVER_PORT -t "$APP_BASE_DIR/web"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
		start
        ;;
	status)
        status
        ;;
    help)
        help
        ;;
	web_start)
		web_start
		;;
	*)
		echo ""
		echo -e "$COLOR_RED ✗ $COLOR_WHITEНеизвестная команда: $COLOR_RED$1$COLOR_WHITE."
		echo -e "Введите$COLOR_YELLOW help$COLOR_WHITE для справки."
		echo ""
		;;
esac
